name: memmap
description: A Linux Dart API for memory mapped buffers.
version: 1.1.0

repository: https://github.com/tercen/memmap

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  ffi: ^2.1.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
